MetaNodeVersion: "0.0.1.0"

NodeConnectionAddress: "node"
ParentConnectionAddress: "rpc-proxy-sequoia.iqnb.com:4200"
ParentConnectionType: "client"
ConnectionAddress_: "0x1eF5a8c5403c5aA1d43a8DC9eD391351012551Cf"
ChainId: 991

StorageAddress: "da7284faC5E804F8b9d71Aa39310f0f86776b51d"
StorageConnectionAddress: "storage"

AdminAddress: "3559d5c1af36faf5cb1dd1587b3c5f93b4c83508"
PrivateKeyAdmin : "72b39b431b74fdfc30a1b5adc5eeb9cc37abe0ca0794d68c4ee57f7d4837cb26"
AuthAddress: "0x9DD2b3aA837569052D5B427D755195b4179F9Cec"

AuthAbiPath: "./auth.abi"
RpcURL: "https://rpc-proxy-sequoia.iqnb.com:8446"
